### ISSUE TITLE
我有自己的框架，用这个sdk好复杂

### ISSUE THREAD

**Issue by duolaqmeng** [cm-heclouds/OneNET_AIO_c#1]
onenet能不能在代码中提供mqtt 密码token计算的函数，能否提供mqtt payload组包，解包函数。

**Comment by wayne-song** [comment]
主要是目前OneNET支持的接入协议/方式比较多，统一的应用框架更利于维护。对于某一指定协议/接入方式的代码，可以配置后导出特定代码文件来集成到自己的工程中。
token计算可以参考onenet/dev_token.[ch]，里面用到了wolfSSL的一些加密算法接口。如果使用了其它算法库，可自行替换。
如果只需要多协议接入-MQTT组包/解包代码，可以从onenet/iot/mqtt里截取对应的代码。
